/**
 * @file robot_motion_handler.h
 *
 * @copyright 2017 3081 Staff, All rights reserved.
 */

#ifndef PROJECT_ITERATION2_SRC_ROBOT_MOTION_HANDLER_H_
#define PROJECT_ITERATION2_SRC_ROBOT_MOTION_HANDLER_H_

/*******************************************************************************
 * Includes
 ******************************************************************************/
#include "src/event_commands.h"
#include "src/robot_params.h"
#include "src/motion_handler.h"
#include "src/arena_mobile_entity.h"
#include "src/sensor_touch.h"

/*******************************************************************************
 * Namespaces
 ******************************************************************************/
NAMESPACE_BEGIN(csci3081);

/*******************************************************************************
 * Classes
 ******************************************************************************/
/**
 * @brief Class managing an ArenaMobileEntity's speed and heading angle based
 * on collisions and (in the case of Robot) user inputs.
 *
 * Currently, both wheels are always going at maximum speed, and
 * cannot be controlled independently.
 */
class RobotMotionHandler : public MotionHandler {
 public:
  /**
   * @brief Default constructor.
   */
  RobotMotionHandler();

  /**
   * @brief Handling commands from the GraphicsArenaViewer (generated by user
   * keypress).
   *
   * Up arrow increases speed, up to a defined limit.
   * Down arrow decreases speed, down to 0 (no negative speeds).
   * Right arrow changes the heading angle clockwise.
   * Left arrow changes the heading angle counter-clockwise.
   *
   * Maximum speed, speed delta, and angle delta are defined in main.cc.
   *
   * @param cmd The command to be processed.
   */
  void AcceptCommand(enum event_commands cmd);

  /**
  * @brief Update the speed and the heading angle according to the sensor
  * readings.
  *
  * Currently does not change speed.
  *
  * @param st A SensorTouch to be read.
  */
  void UpdateVelocity(SensorTouch st) override;

  /**
   * @brief Getter method for speed.
   *
   * @return The current speed.
   */
  double get_speed() const override { return speed_; }

  /**
   * @brief Setter method for speed.
   *
   * @param sp The new speed.
   */
  void set_speed(double sp) override { speed_ = sp; }

  /**
   * @brief Getter method for heading angle.
   *
   * @return The current heading angle.
   */
  double heading_angle() const override { return heading_angle_; }

  /**
   * @brief Setter method for heading angle.
   *
   * @param ha The new heading angle.
   */
  void heading_angle(double ha) override { heading_angle_ = ha; }

  /**
   * @brief Getter method for the maximum speed.
   *
   * @return The current maximum speed.
   */
  double max_speed() const override { return max_speed_; }

  /**
   * @brief Setter method for the maximum speed.
   *
   * @param ms The new maximum speed.
   */
  void max_speed(double ms) override { max_speed_ = ms; }

  /**
   * @brief Getter method for the maximum angle.
   *
   * @return The current maximum angle.
   */
  double max_angle() const override { return max_angle_; }

  /**
   * @brief Setter method for the maximum angle.
   *
   * @param ma The new maximum angle.
   */
  void max_angle(double ma) override { max_angle_ = ma; }

  /**
   * @brief Getter method for the speed delta.
   *
   * @return The current speed delta.
   */
  double speed_delta() const override { return speed_delta_; }

  /**
   * @brief Setter method for the speed delta.
   *
   * @param sd The new speed delta.
   */
  void speed_delta(double sd) override { speed_delta_ = sd; }

  /**
   * @brief Getter method for the angle delta.
   *
   * @return The current angle delta.
   */
  double angle_delta() const override { return angle_delta_; }

  /**
   * @brief Setter method for the angle delta.
   *
   * @param ad The new angle delta.
   */
  void angle_delta(double ad) override { angle_delta_ = ad; }

 private:
  double heading_angle_;
  double speed_;
  double max_speed_;
  double max_angle_;
  double speed_delta_;
  double angle_delta_;
};

NAMESPACE_END(csci3081);

#endif   // PROJECT_ITERATION2_SRC_ROBOT_MOTION_HANDLER_H_
